In [ ]:
import pandas as pd

In [3]:
df = pd.read_csv('student_performance.csv')

In [4]:
print("Missing values:", df.isna().sum())

Missing values: Student_ID          0
Name                0
Age                 0
Program             0
Python              0
Mathematics         0
Statistics          0
Machine_Learning    0
Attendance          0
dtype: int64

In [ ]:
print("Duplicate rows:", df.duplicated())

Duplicate rows: 0

In [10]:
df.rename(columns={"Student_ID": "Student_ID",
    "Python": "Python_Score",
    "Mathematics": "Mathematics_Score",
    "Statistics": "Statistics_Score",
    "Machine_Learning": "ML_Score",
    "Attendance": "Attendance_Percentage"}, inplace=True)

In [13]:
df = df.astype({
    "Python_Score": "int",
    "Mathematics_Score": "int",
    "Statistics_Score": "int",
    "ML_Score": "int",
    "Attendance_Percentage": "float"
})

In [15]:
print("Data Types:", df.dtypes)

Data Types: Student_ID                   str
Student_Name                 str
Age                        int64
Degree_Program               str
Python_Score               int64
Mathematics_Score          int64
Statistics_Score           int64
ML_Score                   int64
Attendance_Percentage    float64
dtype: object

In [16]:
df.head()

,Student_ID,Student_Name,Age,Degree_Program,Python_Score,Mathematics_Score,Statistics_Score,ML_Score,Attendance_Percentage
0,S001,Ali Khan,20,AI,85,78,92,88,95.0
1,S002,Sara Ahmed,21,AI,72,75,70,80,90.0
2,S003,Ahmed Raza,22,SE,90,88,91,93,96.0
3,S004,Fatima Noor,20,DS,65,70,68,72,85.0
4,S005,Usman Ali,21,AI,78,82,80,76,88.0

In [18]:
for id in df['Student_ID']:
    df["Average_Score"] = (df["Python_Score"] + df["Mathematics_Score"] + df["Statistics_Score"] + df["ML_Score"]) / 4

In [22]:
performance = []

for score in df["Average_Score"]:
    if score >= 90:
        performance.append("Excellent")
    elif score >= 80:
        performance.append("Good")
    elif score >= 70:
        performance.append("Average")
    else:
        performance.append("Needs Improvement")

df["Performance"] = performance

In [23]:
df.head()

,Student_ID,Student_Name,Age,Degree_Program,Python_Score,Mathematics_Score,Statistics_Score,ML_Score,Attendance_Percentage,Average_Score,Performance
0,S001,Ali Khan,20,AI,85,78,92,88,95.0,85.75,Good
1,S002,Sara Ahmed,21,AI,72,75,70,80,90.0,74.25,Average
2,S003,Ahmed Raza,22,SE,90,88,91,93,96.0,90.50,Excellent
3,S004,Fatima Noor,20,DS,65,70,68,72,85.0,68.75,Needs Improvement
4,S005,Usman Ali,21,AI,78,82,80,76,88.0,79.00,Average

In [24]:
df.to_csv('cleaned_student_performance.csv', index=False)